target 'WB' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
    pod 'Alamofire', '~> 4.5'
    pod 'SnapKit', '~> 4.0.0'
    pod 'AFNetworking', '~> 3.1.0'
    pod "pop"
    pod "SDWebImage"
    pod "YYModel"
    pod "FMDB"
    pod "SVProgressHUD"
  # Pods for WB
end